apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-graalvm-app-deployment
spec:
  selector:
    matchLabels:
      app: java-graalvm-app
  replicas: 3
  template:
    metadata:
      labels:
        app: java-graalvm-app
    spec:
      containers:
        - name: java-graalvm-app
          # enter the path to your image, be sure to include the correct region prefix
          image: vcp.ocir.io/idi1o0a010nx/java-graalvm-app:qmtoief
          # image: vcp.ocir.io/idi1o0a010nx/java-graalvm-app:${BUILDRUN_HASH}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: java-graalvm-app-service
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: java-graalvm-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-graalvm-app-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: java-graalvm-app-service
              port:
                number: 8080
